# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  #    service_name:
  #        class: AppBundle\Directory\ClassName
  #        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  app.parse.csv:
    class: ParseCsv\Csv

  app.validator:
    class: AppBundle\Service\Validator\CustomValidator
    arguments: [ '@validator' ]

  app.csv.normalizer:
    class: AppBundle\Normalizer\CSVNormalizer
    tags:
      - { name: serializer.normalizer }

  app.serializer.default:
    class: Symfony\Component\Serializer\Serializer
    arguments:
      0:
        - '@app.csv.normalizer'

  app.import.csv:
    class: AppBundle\Service\CSV\ImportCSVService
    arguments: [ '@doctrine.orm.entity_manager', '@app.validator', '@app.parse.csv', '@app.serializer.default']


